CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(500) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER'
    CHECK (role IN ('ADMIN', 'USER')),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS connection_logs (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               username VARCHAR(50),
    ip_address VARCHAR(100) NOT NULL,
    connected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    disconnected_at TIMESTAMP,
    status VARCHAR(30) NOT NULL
    );

-- The application creates the first admin account if none exists.
-- Do not store a plaintext password in this SQL file.
